import type { Metadata } from 'next'
import LegalLayout from '@/components/LegalLayout'

export const metadata: Metadata = {
  title: 'Medical Disclaimer',
  description: 'Important limits on the health information Medico Me provides.',
}

export default function DisclaimerPage() {
  return (
    <LegalLayout title="Medical Disclaimer" updated="June 17, 2026">
      <p>
        Please read this carefully before relying on anything Medico Me tells you.
      </p>

      <h2>In an emergency, get help now</h2>
      <p>
        If you think you may be having a medical emergency — for example chest pain, trouble
        breathing, severe bleeding, sudden weakness, confusion, or thoughts of self-harm —{' '}
        <strong>call your local emergency number or go to the nearest emergency department
        immediately.</strong> Do not wait for the app.
      </p>

      <h2>Not professional medical advice</h2>
      <p>
        Medico Me provides general, informational health content and an automated symptom check for
        convenience and education. It is <strong>not</strong> a substitute for professional medical
        advice, diagnosis, or treatment, and it is not a medical device. Using the app does not
        create a doctor–patient relationship.
      </p>

      <h2>Always consult a clinician</h2>
      <p>
        Always seek the advice of a physician or other qualified health provider with any questions
        about a medical condition. Never disregard professional medical advice, or delay seeking it,
        because of something you read here.
      </p>

      <h2>Limits of the AI assistant</h2>
      <p>
        The chat assistant&rsquo;s free-text responses are generated by an AI model. AI can be
        incomplete, out of date, or simply wrong, and it does not know your full medical history. Its
        suggestions — including any home-care tips, over-the-counter options, or specialist
        referrals — are starting points for a conversation with a real clinician, not prescriptions
        or definitive diagnoses.
      </p>

      <h2>No reliance</h2>
      <p>
        Any action you take based on the information in Medico Me is strictly at your own risk. We
        are not responsible for outcomes resulting from reliance on the Service.
      </p>
    </LegalLayout>
  )
}
